#!/bin/bash
# =====================================
# BUILD-IMAGE.SH - Container Image Building
# =====================================
# This script builds the container image using podman with proxy handling.
# It manages proxy environment variables and executes the podman build command.
#
# Usage:
#   ./scripts/build-image.sh
#
# Dependencies:
#   - lib/common.sh (for colors and logging)
#   - lib/env-loader.sh (for .env loading)
#   - lib/proxy-handler.sh (for proxy configuration)
#   - Podmanfile (generated by generate-podmanfile.sh)

set -e

# Source required libraries
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=../lib/common.sh
source "$PROJECT_ROOT/lib/common.sh"
# shellcheck source=../lib/env-loader.sh
source "$PROJECT_ROOT/lib/env-loader.sh"
# shellcheck source=../lib/proxy-handler.sh
source "$PROJECT_ROOT/lib/proxy-handler.sh"

# =====================================
# CONFIGURATION
# =====================================
readonly PODMANFILE="$PROJECT_ROOT/Podmanfile"

# Note: DEFAULT_TTYD_PORT is defined in lib/common.sh

# =====================================
# HELPER FUNCTIONS
# =====================================

# Check if Podmanfile exists
check_podmanfile() {
    if [ ! -f "$PODMANFILE" ]; then
        log_error "Podmanfile not found at $PODMANFILE"
        log_info "Run 'make generate-all' or './scripts/generate-podmanfile.sh' first"
        exit 1
    fi
}

# Build podman build arguments based on proxy configuration
# Uses library function to avoid code duplication
build_podman_args() {
    # Use centralized proxy handler from lib/proxy-handler.sh
    prepare_all_proxy_args
}

# Clear proxy environment variables if build proxy is disabled
# Uses library functions to avoid code duplication
clear_proxy_environment() {
    # Use centralized proxy handler from lib/proxy-handler.sh
    unset_host_proxies
    clear_podman_machine_proxy
}

# Execute the podman build command
execute_build() {
    local build_args=$1
    
    log_info "Building container image: ${CONTAINER_NAME}"
    log_info "This may take a few minutes..."
    echo ""
    
    # Show build command for debugging
    log_debug "Build command: podman build ${build_args} -f Podmanfile -t ${CONTAINER_NAME} ."
    echo ""
    
    # Execute build
    if podman build ${build_args} -f Podmanfile -t "${CONTAINER_NAME}" .; then
        return 0
    else
        return 1
    fi
}

# Display success message with next steps
show_success() {
    echo ""
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    log_success "Build Complete!"
    echo ""
    
    log_info "Container image: ${BLUE}${CONTAINER_NAME}${NC}"
    echo ""
    
    log_info "Next steps:"
    echo ""
    echo -e "  ${YELLOW}Start with compose:${NC}"
    echo "    make up"
    echo ""
    echo -e "  ${YELLOW}Or run directly:${NC}"
    echo "    podman run -d -p ${TTYD_PORT}:${DEFAULT_TTYD_PORT} \\"
    
    # Add Claude Code env vars if configured
    if [ -n "$ANTHROPIC_BASE_URL" ]; then
        echo "      -e ANTHROPIC_BASE_URL='${ANTHROPIC_BASE_URL}' \\"
    fi
    if [ -n "$ANTHROPIC_AUTH_TOKEN" ]; then
        echo "      -e ANTHROPIC_AUTH_TOKEN='${ANTHROPIC_AUTH_TOKEN}' \\"
    fi
    if [ -n "$ANTHROPIC_MODEL" ]; then
        echo "      -e ANTHROPIC_MODEL='${ANTHROPIC_MODEL}' \\"
    fi
    if [ -n "$ANTHROPIC_SMALL_FAST_MODEL" ]; then
        echo "      -e ANTHROPIC_SMALL_FAST_MODEL='${ANTHROPIC_SMALL_FAST_MODEL}' \\"
    fi
    
    echo "      --name ${CONTAINER_NAME} ${CONTAINER_NAME}"
    echo ""
    echo -e "  ${YELLOW}Access terminal:${NC}"
    echo "    http://localhost:${TTYD_PORT}"
    echo ""
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

# Display failure message with debugging info
show_failure() {
    local build_args=$1
    
    echo ""
    echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    log_error "Build Failed"
    echo ""
    
    log_info "Debug Information:"
    echo "  Build args: ${build_args}"
    echo "  Container name: ${CONTAINER_NAME}"
    echo "  Podmanfile exists: $(test -f "$PODMANFILE" && echo "yes" || echo "no")"
    echo ""
    
    if [ -f "$PODMANFILE" ]; then
        log_info "Podmanfile first 20 lines:"
        head -20 "$PODMANFILE" | sed 's/^/  /'
        echo ""
    fi
    
    echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

# =====================================
# MAIN EXECUTION
# =====================================

main() {
    print_header "Container Image Build"
    
    # Load and validate environment
    load_and_validate_env
    
    # Check prerequisites
    check_podmanfile
    
    # Build podman arguments
    local build_args
    build_args=$(build_podman_args)
    
    log_debug "Final build arguments: ${build_args}"
    echo ""
    
    # Clear proxy environment if needed
    clear_proxy_environment
    
    # Execute build
    if execute_build "$build_args"; then
        show_success
        exit 0
    else
        show_failure "$build_args"
        exit 1
    fi
}

# Run main function
main "$@"